site_name: Dune Docs
site_url: https://dune.com/docs
repo_url: https://github.com/duneanalytics/docs
site_dir: site/docs
theme:
  language: en
  name: material
  custom_dir: overrides
  logo: images/dune-icon-only.png
  favicon: images/dune-icon-only.png
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - toc.follow
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
nav:
  - ...
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - awesome-pages
  - mkdocs-video
  - redirects:
      redirect_maps:
        #4/1/2022 Rework
       'reference/dune-v2/index.md': 'query/index.md'
       'reference/dune-v2/query-engine.md': 'query/syntax-differences.md'
       'reference/dune-v2/dunesql-changes.md': 'query/dunesql-changes.md'
       'getting-started/index.md': 'index.md'
       'dune-engine-v2-beta/abstractions-in-dunev2/getting-started-contribute-a-spell/README.md': 'data-tables/spellbook/contributing/index.md'
       'bounties/wizard-request-program.md': 'reference/dune-bounties.md'
       'data-tables/data-tables/raw-data/ethereum-data.md': 'data-tables/raw/index.md'
       'about/tutorials/dune-guides/tips.md': 'analytics_guidelines.md'
       'about/tutorials/video-series.md': 'app/index.md'
       'dune-engine-v2-beta/dunes-new-query-engine.md': 'query/index.md'
       'about/tutorials/sql-guides.md': 'index.md'
       'data-tables/solana-data/README.md': 'data-tables/raw/solana/index.md'
       'data-tables/evm-blockchains/decoded-data/README.md': 'data-tables/decoded/index.md'
       'data-tables/abstractions/labels.md': 'ata-tables/spellbook/top-tables/labels.md'
       'data-tables/data-tables/nft.trading.md': 'data-tables/spellbook/top-tables/nft.trades.md'
       'data-tables/abstractions/special-tables/README.md': 'data-tables/spellbook/top-tables/tokens.md'
       'data-tables/abstractions/erc-20-balances.md': 'data-tables/spellbook/top-tables/tokens.md'
       'data-tables/abstractions/README.md': 'data-tables/spellbook/index.md'
       'data-tables/data-tables/raw-data/xdai-data.md': 'data-tables/index.md'
       'data-tables/spells/prices.md': 'data-tables/spellbook/top-tables/prices.md'
       'data-tables/data-tables.md': 'data-tables/index.md'
       'data-tables/user-generated.md': 'data-tables/index.md'
       'dune-engine-v2-beta/query-engine.md': 'query/index.md'
       'dune-engine-v2-beta/dunes-new-query-engine/query-engine.md': 'query/index.md'
       'about/tutorials/queries.md': 'app/index.md'
       'about/tutorials/README.md': 'index.md'
       'dune-engine-v2-beta/abstractions-in-dunev2/introducing-spellbook.md': 'data-tables/spellbook/index.md'
       'data-tables/evm-blockchains/README.md': 'data-tables/index.md'
       'data-tables/abstractions/labels.md': 'data-tables/spellbook/index.md'
       'data-tables/user-generated.md': 'data-tables/index.md'
       'duneapp/teams.md': 'app/teams.md'
       'about/tutorials/queries/price-queries.md': 'data-tables/spellbook/top-tables/prices.md'
       'data-tables/evm-blockchains/decoded-data/README.md': 'data-tables/decoded/index.md'
       'duneapp/parameters.md': 'app/queries/parameters.md'
       'data-tables/community/README.md': 'data-tables/community/index.md'
       'data-tables/abstractions/nft.trading.md': 'data-tables/spellbook/top-tables/nft.trades.md'
       'duneapp/dashboards.md': 'app/dashboards/index.md'
       'about/tutorials/dune-guides/README.md': 'app/index.md'
       'dune-engine-v2-beta/abstractions-in-dunev2/README.md': 'data-tables/spellbook/index.md'
       'faq/does-dune-have-an-api.md': 'reference/faq/does-dune-have-an-api.md'
       'duneapp/visualizations/pie-charts.md': 'app/visualizations/charts-graphs.md'
extra:
  generator: false
  alternate:
    - name: English
      link: /docs
      lang: en
    - name: 简体中文
      link: zh/
      lang: zh
  analytics:
    provider: posthog
    api_key: !ENV POSTHOG_API_KEY
    api_host: !ENV POSTHOG_API_HOST
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js