INHERIT: ../mkdocs.yml
site_url: https://dune.com/docs/zh
theme:
  language: zh
  name: material
  custom_dir: ../overrides
  logo: images/dune-icon-only.png
  favicon: images/dune-icon-only.png
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    # - toc.integrate
    # - toc.follow
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
  plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - awesome-pages
    - mkdocs-video
    - social